language: java
jdk: oraclejdk8

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -e MYSQL_ROOT_PASSWORD=example -p 127.0.0.1:3306:33060 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      script: mvn test -Dtest=com.napier.sem.AppTest