language: java
jdk: oraclejdk8

install: true
script:
  - "mvn cobertura:cobertura"
  - mvn clean install

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN