version: '3'
services:
  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # web is in web folder
  web:
    build: web/.
    ports:
      - "80:80"